/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0c472ecb715bf92724671514cd84abf7)
interface __BaseEnv_Env {
	WRITES_ENABLED: "false";
	SPLIIT_TIMEOUT_MS: "15000";
	DRAFT_TTL_SECONDS: "600";
	ALLOWED_HOSTNAMES: "";
	ALLOWED_SPLIIT_HOSTNAMES: "spliit.app";
	MCP_AUTH_TOKEN: string;
	ADMIN_TOKEN: string;
	DATA_ENCRYPTION_KEY: string;
	SPLIIT_GROUPS_JSON: string;
	SPLIIT_STATE: DurableObjectNamespace<import("./src/server").SpliitState>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "SpliitState";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WRITES_ENABLED" | "SPLIIT_TIMEOUT_MS" | "DRAFT_TTL_SECONDS" | "ALLOWED_HOSTNAMES" | "ALLOWED_SPLIIT_HOSTNAMES" | "MCP_AUTH_TOKEN" | "ADMIN_TOKEN" | "DATA_ENCRYPTION_KEY" | "SPLIIT_GROUPS_JSON">> {}
}
