/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 367ab676a7601e029f9500f82b0dad22)
interface __BaseEnv_Env {
	WRITES_ENABLED: "false";
	SPLIIT_TIMEOUT_MS: "15000";
	ALLOWED_HOSTNAMES: "";
	MCP_AUTH_TOKEN: string;
	SPLIIT_GROUPS_JSON: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WRITES_ENABLED" | "SPLIIT_TIMEOUT_MS" | "ALLOWED_HOSTNAMES" | "MCP_AUTH_TOKEN" | "SPLIIT_GROUPS_JSON">> {}
}
